### PR TITLE
fix: broken `defaultDocs` properties

### LINKED ISSUE #300: Broken docs index links for Table, Virtual and Ranger
## Expected Behavior

For a valid `libraryId`, Going to `/$libraryId/latest/docs` should resolve to a index route for each library

## Reproduction

navigate to e.g. https://tanstack.com/table/latest/docs and get an index page

## Correct Links

Please feel free to test these redirects yourself

- https://tanstack.com/router/latest/docs -> https://tanstack.com/router/latest/docs/framework/react/overview 200  ✅ 
- https://tanstack.com/query/latest/docs -> https://tanstack.com/query/latest/docs/framework/react/overview 200 ✅
- https://tanstack.com/form/latest/docs -> https://tanstack.com/form/latest/docs/overview 200 ✅
- https://tanstack.com/store/latest/docs -> https://tanstack.com/store/latest/docs/overview 200 ✅
- https://tanstack.com/config/latest/docs -> https://tanstack.com/config/latest/docs/overview 200 ✅

## Broken Links

- https://tanstack.com/table/latest/docs -> https://tanstack.com/table/latest/docs/framework/react/overview 404 ❌
- https://tanstack.com/virtual/latest/docs -> https://tanstack.com/virtual/latest/docs/framework/react/overview 404 ❌
- https://tanstack.com/ranger/latest/docs -> https://tanstack.com/ranger/latest/docs/framework/react/overview 404 ❌

## Expected Link Behavior

Assuming that the link from the `Get Started` button on `$libraryId/latest` is meant to be the canonical index link:

- https://tanstack.com/table/latest/docs -> https://tanstack.com/table/latest/docs/introduction 200  ✅ 
- https://tanstack.com/virtual/latest/docs -> https://tanstack.com/virtual/latest/docs/introduction 200  ✅ 
- https://tanstack.com/ranger/latest/docs -> https://tanstack.com/ranger/latest/docs/overview 200  ✅ 

## Won't fix

I'm only fixing for libarys that have the `Get Started` link button on there home pages:

- https://tanstack.com/start/latest/docs/overview - `Something went wrong`
  - Start docs are a sub division of the Router docs and do not have there own `Get Started` link, so `start` is not a valid `libraryId`
- https://tanstack.com/foo/latest/docs/overview or whatever - 404
  - This seems like expected behavior for non-valid library ids

## Action items

- [x] I am willing to submit a PR to fix this issue.

### PR DESCRIPTION
**Pull request by DogPawHat**
fixes #300

### CODE REVIEW

File: app/libraries/config.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import { Library } from '.'
 
-export const configProject: Library = {
+export const configProject = {
```
Comment (DogPawHat) [inline app/libraries/config.ts:3]: `satisfies` is generally nicer but I'm aware that it's slower then doing the explicit typing. willing to revert.

Comment (DogPawHat) [reply app/libraries/config.ts:3]: wait, this is application code not a library. I think it's fine then.

**Review by SeanCassiere — APPROVED** [review]

**Comment by DogPawHat** [comment]
Thanks!
